### ISSUE TITLE
create teaser page

### ISSUE THREAD

**Issue by skeep** [skeep/jscweb-2016#2]

**Comment by divyamkhurana** [comment]
![js conference style1](https://cloud.githubusercontent.com/assets/4456424/11654247/291253ae-9dca-11e5-8a06-08ba603776b3.png)

**Comment by skeep** [comment]
can we use 2015 images as background? - https://www.flickr.com/photos/100543192@N08/sets/72157656673572946

**Comment by skeep** [comment]
also how the UI will show for mobile and portrait mode?

**Comment by divyamkhurana** [comment]
I couldn't find the image that I was looking for, that's why used this one.
I'll share another concept by EOD & then we can pick one. For that, I'll work on the mobile & tablet screens.

**Comment by toamitkumar** [comment]
very good first draft, let's have a few more options 

@skeep @divyamkhurana -- date is 15 & 16th July

**Comment by divyamkhurana** [comment]
![js-conference](https://cloud.githubusercontent.com/assets/4456424/11662384/5882086e-9dfc-11e5-99f3-9148fe3e7486.png)

This is still work in progress.

@toamitkumar - will update the date.

**Comment by skeep** [comment]
how the pages will look in mobile?

**Comment by skeep** [comment]
might wana try including https://www.youtube.com/watch?v=3ZOrrQt0WZw, amybe as a link or directly on the page

**Comment by toamitkumar** [comment]
@skeep yes, the promo video would be good on the teaser page

**Comment by divyamkhurana** [comment]
I almost finished these when the video thing came up. I've added the video link next to social login's for now.

![js conference - style2 - v1](https://cloud.githubusercontent.com/assets/4456424/11713081/1c186f1a-9f57-11e5-9669-83c4a4ac384e.png)
![js conference - style2 - v2](https://cloud.githubusercontent.com/assets/4456424/11713082/1c1a876e-9f57-11e5-83f3-11b2bed53d5e.png)
![js conference - style3](https://cloud.githubusercontent.com/assets/4456424/11713080/1c14f128-9f57-11e5-8e4d-8fe68ba3ab67.png)

**Comment by divyamkhurana** [comment]
Can we please select a concept on which we'll improvise further & do mobile/tab screens.

**Comment by rgabs** [comment]
I really like the last one, specially the overlay color.

On Thu, Dec 10, 2015 at 4:03 PM, Divyam Khurana notifications@github.com
wrote:

> Can we please select a concept on which we'll improvise further & do
> mobile/tab screens.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skeep/jscweb-2016/issues/2#issuecomment-163570929.

## 

Thanks and Regards
Rahul Gaba
7838275450

**Comment by skeep** [comment]
I like the first one actually.
I am not fan of the overlay color though, too monotonous IMHO. But I like the space, symmetry and typography.

Video link ok for now.
I would still emphasize on using images from our conference.

**Comment by skeep** [comment]
https://flic.kr/s/aHsk1cXm4p this 2014 album, if you dont find good ones in 2015.

Suman

**Comment by pallavichauhan** [comment]
I like the 1st style and the 3rd overlay color. Should we tone down the color a bit? For me, it was a bit overwhelming and the focus on event details was lost somehow.

**Comment by skeep** [comment]
@divyamkhurana complete unedited 2014 album -> https://www.flickr.com/photos/100543192@N08/albums/

**Comment by skeep** [comment]
so we are finalizing on below designs.

### Web

![jscc_v7](https://cloud.githubusercontent.com/assets/425732/11847842/650afd3a-a445-11e5-9742-417eb7f03583.png)

### Tab potrait

![tab portrait](https://cloud.githubusercontent.com/assets/425732/11847851/6bcf8dc0-a445-11e5-8530-268c716e13b7.png)

### Mobile Potrait

![mobile portrait](https://cloud.githubusercontent.com/assets/425732/11847857/6f228888-a445-11e5-9774-02f77544a91b.png)

**Comment by skeep** [comment]
design complete

**Comment by rgabs** [comment]
@divyamkhurana Please share the background image
